# A first workflow to play with the editor
name: My First Workflow
on: 
  push:
    branches: 
      - main 
  workflow_dispatch:
jobs:
  first_job:
    name: My first job
    runs-on: ubuntu_latest
    steps:
      - run: echo "Hello World from ${{ github.actor }}."      
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree
  
